[project]
name = "official-mcp-registry-database"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "marimo>=0.15.5",
    "pandas>=2.3.2",
    "seaborn>=0.13.2",
    "sqlalchemy>=2.0.43",
]
